// <auto-generated />
using System;
using HttpPatchSample.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HttpPatchSample.Migrations
{
    [DbContext(typeof(HttpPatchSampleDbContext))]
    [Migration("20200511143756_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("HttpPatchSample.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FatherId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MotherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HttpPatchSample.Database.User", b =>
                {
                    b.HasOne("HttpPatchSample.Database.User", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId");

                    b.HasOne("HttpPatchSample.Database.User", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId");
                });
#pragma warning restore 612, 618
        }
    }
}
